---
# SPDX-License-Identifier: MIT

name: 'Check'
description: 'Rust checks'
inputs:
  working-directory:
    description: 'Directory to run commands in'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: format
      working-directory: ${{ inputs.working-directory }}
      run: cargo fmt --check
      shell: bash

    - name: lint
      working-directory: ${{ inputs.working-directory }}
      run: cargo clippy -- -D warnings
      shell: bash

    - name: build
      working-directory: ${{ inputs.working-directory }}
      run: cargo build --release
      shell: bash

    - name: test
      working-directory: ${{ inputs.working-directory }}
      run: cargo test
      shell: bash
